### ISSUE TITLE
Roadmap to version 1.0.0

### ISSUE THREAD

**Issue by sithmel** [sithmel/json-key-value#2]
- [x] tokenizer
- [x] streamToSequence works with buffer instead of strings
- [x] maxDepth for chunk sequence (streamToSequence)
- [x] maxDepth for chunk sequence (ObjectToSequence)
- [x] chunk sequence works with SequenceToObject
- [x] chunk sequence works with SequenceToStream
- [x] sequenceToStream to output a stream
- [x] include and exclude in streamToSequence
- [x] include and exclude in ObjectToSequence
- [x] tests
- [x] documentation

json-key-value-wasm
- [x] tokenizer
- [ ] matcher
- [ ] StreamToSequence
- [ ] StreamToStream
- [ ] SeqToStream
- [ ] benchmarks
- [ ] documentation

**Comment by sithmel** [comment]
Remaining points to be copied to [json-key-value-wasm](https://github.com/sithmel/json-key-value-wasm)

**Comment by sithmel** [comment]
done
